---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: '10'

inputs:
- name: source
- name: version

outputs:
- name: dist

run:
  path: source/pipeline/build.sh

params:
  CYPRESS_USERNAME:
  CYPRESS_PASSWORD:

caches:
  - path: ../../../root/.cache
  - path: ../../../root/.npm
