---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: '10'

inputs:
- name: source
- name: version

outputs:
- name: dist

run:
  path: source/pipeline/build.sh