---
jobs:
- name: build-and-publish
  public: true
  plan:
  - get: source
    trigger: true
    params:
      depth: 1
  - put: version
    params:
      bump: patch
  - task: build
    file: source/pipeline/build.yml
  - put: npm-registry
    params:
      username: {{npm-username}}
      password: {{npm-password}}
      email: engineering@boclips.com
      path: dist

resources:
- name: source
  type: git
  source:
    branch: master
    private_key: {{boclips-js-security-repo-key}}
    uri: git@github.com:knowledgemotion/boclips-js-security.git

- name: version
  type: semver
  source:
    initial_version: "1.0.4"
    driver: git
    uri: git@github.com:knowledgemotion/versions.git
    branch: master
    file: boclips-js-security
    private_key: {{versions-repo-key}}

- name: npm-registry
  type: npm-resource
  source:
    package_name: boclips-js-security

resource_types:
- name: npm-resource
  type: docker-image
  source:
    repository: idahobean/npm-resource